Avoid tcp port conflicts in tests
```
X bloop.bsp.TcpBspConnectionSpec.initialize several clients concurrently and simulate a hard disconnection 932ms
478s
721
  java.net.BindException: Address already in use (Bind failed)
478s
722
  java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:-2)
478s
723
  java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
478s
724
  java.net.ServerSocket.bind(ServerSocket.java:381)
478s
725
  java.net.ServerSocket.<init>(ServerSocket.java:243)
478s
726
  bloop.io.ServerHandle$Tcp.<init>(ServerHandle.scala:26)
478s
727
  bloop.io.ServerHandle$Tcp$.apply(ServerHandle.scala:35)
478s
728
  bloop.bsp.BspServer$.run(BspServer.scala:259)
478s
729
  bloop.bsp.BspBaseSuite.openBspConnection(BspBaseSuite.scala:421)
478s
730
  bloop.bsp.BspConnectionSpec.$anonfun$new$3(BspConnectionSpec.scala:40)
478s
731
  scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
478s
732
  monix.eval.internal.TaskRunLoop$.monix$eval$internal$TaskRunLoop$$loop$1(TaskRunLoop.scala:187)
478s
733
  monix.eval.internal.TaskRunLoop$RestartCallback$1.onSuccess(TaskRunLoop.scala:119)
478s
734
  monix.eval.Task$.$anonfun$forkedUnit$2(Task.scala:1463)
478s
735
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
478s
736
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
478s
737
  java.lang.Thread.run(Thread.java:834)
```