Fix bloopGenerate definition in scala/scala
Error:

```scala
/drone/.sbt/1.0/staging/6a8c90d140e2ff5a7832/scala/build.sbt:322: error: type mismatch;
 found   : Unit
 required: sbt.File
    (which expands to)  java.io.File
  bloopGenerate in Compile := {()},
                               ^
/drone/.sbt/1.0/staging/6a8c90d140e2ff5a7832/scala/build.sbt:323: error: type mismatch;
 found   : Unit
 required: sbt.File
    (which expands to)  java.io.File
  bloopGenerate in Test := {()}
                            ^
sbt.compiler.EvalException: Type error in expression
```