add missing scala-xml dependency in shaded launcher
Similar to #1109 #1110 this _should_ fix a `java.lang.NoClassDefFoundError: scala/xml/Node` error encountered when using the launcher in some situations. I haven't figured out when exactly this error occurs and this change is untested.