Look for java.exe path when resolving java binary
It looks the previous logic would fail in in certain Windows systems
where the Windows Search is disabled, with a similar error to this one:

```
java.lang.IllegalStateException: Missing java executable at C:\Program Files\Java\jdk1.8.0_202\jre\bin\java!
  bloop.exec.JvmForker.javaExecutable(JvmProcessForker.scala:133)
  bloop.exec.JvmForker.runMain(JvmProcessForker.scala:114)
  bloop.exec.JvmProcessForker.runMain(JvmProcessForker.scala:56)
  bloop.exec.JvmProcessForker.runMain$(JvmProcessForker.scala:44)
  bloop.exec.JvmForker.runMain(JvmProcessForker.scala:90)
```

This bug intends to avoid throwing that exception by resolving
`java.exe` instead of just `java`.